# Generated by Django 4.2 on 2023-05-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_customer_remove_ticket_consultant_remove_ticket_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
